### ISSUE TITLE
Domain model control over asset palette categorization

### ISSUE THREAD

**Issue by mike1813** [Spyderisk/system-modeller#101]
At present, the palette of asset types displayed in the system-modeller editor window is created by finding the subclass of `core:asset` of which each assertible asset class is a descendent. This subclass of `core:asset` is taken as the palette category in which to display the asset type in the palette.

This means that (for example) every type of Host must be displayed together in the Hosts palette group, every Process in the Processes palette group, and so forth. That isn't always the best option.

For example, the domain-network submodel for Cloud Management currently uses specialised Host subclasses to represent Kubernetes Master, Worker, Pod and Container components, Process subclasses for the Kubernetes API Server and Ingress proxy, and a NetworkAsset subclass representing the ClusterIP overlay network between the Master VM and running Pods. Ideally, those asset classes would be in a separate 'Cloud' group.

The domain model does contain a mechanism to handle this. Alongside the asset class hierarchy descended from `core:Asset` there is a separate 'overlay' hierarchy descended from `core:PaletteType`. So setting `?category rdfs:subClassOf core:PaletteType` would provide a means for the domain model to specify a palette grouping based on any criterion.

At present, each assertible asset has only one palette 'category'. That restriction can be respected by domain modellers at least to begin with. Later, we may want to allow each asset to appear in more than one 'category', but this may require more extensive changes, so can be left as a separate issue.

**Comment by mike1813** [comment]
This has come up again, and the requirement has changed.

To create viable interfaces between domain model submodels (packages), we need to create a cleaner asset class hierarchy, so that asset classes in one package provide base classes that can be used when defining assets or relationships in a dependent package. Overlay parent classes create problems with this, so we'll need to make every class containing assets a subclass of core:Asset if we want anything resembling a definable interface between domain model packages in the short term.

This makes it far more difficult to arrange for each assertible asset class to be descended from an appropriate top-level subclass of core:Asset.

The proposed solution is to make palette groups into direct subclasses of core:Asset, as part of a 'Core' package. System modeller should then be able to extract these palette groups without modification.

However, we will also need to make other overlay parent classes into subclasses of core:Asset, but without having them treated by system modeller as palette groups. This would be a disaster because each overlay parent contains many, often disparate assets as direct or indirect subclasses, and we don't want them appearing as arbitrary and confusing palette groups.

I propose to make all other overlay parent classes subclasses of core:AssetOverlay, and make that a direct subclass of core:Asset so everything is descended from core:Asset. But because core:AssetOverlay would be a direct descendent of core:Asset, it would then be treated by system modeller as a palette group which would contain pretty much every assertible asset subclass.

The new requirement is therefore that system modeller should ignore the core:AssetOverlay class when creating palette groups.

@kenmeacham : can this be done reasonably quickly? I hope it would just require a couple of lines in core.rdf and a simple test in the palette generation code to exclude this URI from the set of palette groups.

**Comment by mike1813** [comment]
@kenmeacham : some notes following our conversation.

In any recent release on branch v6a, every assertible asset (core#isAssertable = true) has a parent that is a subclass of core#PaletteType. Right now:

- each assertible asset has only one such parent
- each of those parents is a direct subclass of core#PaletteType
- the groups of assets identified by these parent classes are the same as the ones we get by looking for subclasses of core:Asset

The resource core#PaletteType is currently NOT included in the core model definition in the system modeller code base (core.rdf). I guess that will need to be added. It is NOT a subclass of core#Asset. It is in effect a sibling of core:Asset, so we could do worse than make it a copy of core#Asset with a different URI.

Once that has been done, it should be possible to look for direct subclasses of core#PaletteType to make into palette groups, instead of looking for direct subclasses of core#Asset. All direct subclasses of core#PaletteType in recent domain models:

- have a rdfs#label property that can be used as the title of the palette group (in the same way as we do for subclasses of core#Asset)
- has an rdfs#comment property that can be used as a tool tip explaining the group, if desired.

At present, there seems to be no tool tips attached to palette groups, so there is no need to use the rdfs#comment property for that purpose. It is just something you could do if you felt like it.

**Comment by kenmeacham** [comment]
I have adjusted the query that gets the palette assets to use core#PaletteType. This seems to work fine, and the GUI now groups the assets in the palette accordingly. The following screenshots show a before / after. You can see that the asset groups are now defined by the palette type. In this example, the Juristiction asset has now moved into the "Users and Governance" group:

Before fix:
![Image](https://github.com/user-attachments/assets/1794f8c2-73ff-4e71-87fc-8036a2f6285a)

After fix:
![Image](https://github.com/user-attachments/assets/ea14a7dd-f7d3-4e68-b7ee-06012506d420)

**Comment by kenmeacham** [comment]
> The resource core#PaletteType is currently NOT included in the core model definition in the system modeller code base (core.rdf). I guess that will need to be added. It is NOT a subclass of core#Asset. It is in effect a sibling of core:Asset, so we could do worse than make it a copy of core#Asset with a different URI.

I have added PaletteType  to the core model as follows. 

```
  <owl:Class rdf:ID="PaletteType">
    <rdfs:subClassOf>
      <owl:Class rdf:about="#CompositeThing"/>
    </rdfs:subClassOf>
    <rdfs:comment>Defines a group of assets in the GUI palette.</rdfs:comment>
    <rdfs:label>PaletteType</rdfs:label>
  </owl:Class>
```

@mike1813 -  Does this seem correct, to make this a subClass of #CompositeThing?

> Once that has been done, it should be possible to look for direct subclasses of core#PaletteType to make into palette groups, instead of looking for direct subclasses of core#Asset. All direct subclasses of core#PaletteType in recent domain models:
> 
>     * have a rdfs#label property that can be used as the title of the palette group (in the same way as we do for subclasses of core#Asset)
> 
>     * has an rdfs#comment property that can be used as a tool tip explaining the group, if desired.
> 
> 
> At present, there seems to be no tool tips attached to palette groups, so there is no need to use the rdfs#comment property for that purpose. It is just something you could do if you felt like it.

I considered this, however this would mean restructuring the palette returned to the GUI, as we currently don't include the description (comment) for any "category". Furthermore, the contents don't seem so useful at the moment anyway, e.g.

```
<http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#DataPalette> <http://www.w3.org/2000/01/rdf-schema#comment> "An overlay parent class descended from Palette Type, to be used to control the grouping of assertable assets in the SSM GUI Asset Palette." <http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain-network> .
```
