### ISSUE TITLE
Add filters for Control and Control Strategy lists

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#102]
It would be useful to have a way to only show the Controls and Control Strategies where one or more of the control/control strategy type is active.

It's not uncommon to want to check a model to see what controls and control strategies you have set, and right now you have to look down the list to spot the ones which do not have "0 of xxx" after them.

**Comment by scp93ch** [comment]
Similarly to the filter on the Assets list ("Only asserted assets"), we could have "Only asserted controls" and "Only asserted control strategies".

What we actually should show though is, for the controls for example, just those controls where 1 or more of the instances are asserted. For example, without the filter we would have:

* ControlFoo : 0 of 3
* ControlBar : 1 of 5

With the filter on:

* ControlBar : 1 of 5

and similarly for the Control Strategies.

The filter should be unselected by default.

**Comment by kenmeacham** [comment]
I've implemented filters for both controls and control strategies. As it seemed hard to spot the controls, etc that were enabled, I've made them bolder in the list too. I also thought it would be useful to add text search at the same time. This all seems to work fine. Some screenshots below:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/402d99fe-9d00-4ae8-8791-58cec5791ca5)
![image](https://github.com/Spyderisk/system-modeller/assets/50845365/8bc884d7-d9cb-4d94-a709-daf825266c88)
![image](https://github.com/Spyderisk/system-modeller/assets/50845365/6f7bb71b-af8a-4c54-af4b-5822f4c6af81)
![image](https://github.com/Spyderisk/system-modeller/assets/50845365/4b5073b8-948b-4eb3-908c-3dba9b516726)
![image](https://github.com/Spyderisk/system-modeller/assets/50845365/2ef644b6-66a7-4bcf-a8f9-23e73b429f64)
