### ISSUE TITLE
Secondary Consequences not initially displayed in Threat Explorer

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#108]
When a Threat is opened in the Threat Explorer, the Secondary Consequences area is closed initially. Upon opening it, there are no Consequences shown and it states "No consequences found". Clicking on the "Show filters" or "Reset sort" buttons then causes the list of Consequences to be displayed.

**Comment by scp93ch** [comment]
I believe this used to also happen in the main Consequences panel sometimes (on the right hand side) but I haven't seen that in a while.

**Comment by kenmeacham** [comment]
For some reason I am not seeing this issue, at least on the example model I am using. If I open the Secondary Consequences panel on a threat that certainly has them, they always appear straight away. Some threats don't have secondary consequences, so these lists always remain empty, whatever options I select.

Could you demonstrate the problem to me and send me the example you are using, i.e. which particular threat is showing this issue?

Which browser are you using?

**Comment by scp93ch** [comment]
I am using Brave (based on Chrome). I've attached the full model: [ACME Sales (1) 2023-11-14T10_54.nq.gz](https://github.com/Spyderisk/system-modeller/files/13347868/ACME.Sales.1.2023-11-14T10_54.nq.gz)

If I load the model, click on the highest risk consequence (loss of confidentiality of customer data) and then, on the Consequence Explorer, click on the root cause Threat (Execution of malicious email attachment by "Email Client" on "Laptop" in "Company Premises") the the Threat Explorer opens. The Secondary Consequences accordion entry is closed by default, opening it reveals:

![image](https://github.com/Spyderisk/system-modeller/assets/4892991/8cb78867-43b6-4a1f-ab9b-ebb20159154c)

Clicking on "Reset Filters" then shows a load of Consequences.

If I close the Threat Explorer and click on the root cause in the Consequence Explorer again, this time round I get: 

![image](https://github.com/Spyderisk/system-modeller/assets/4892991/0fd27bdd-19c0-4de5-bc88-b4741751e7c6)

It seems that sometimes the list of Consequences appears by itself, after initially not being there.

**Comment by kenmeacham** [comment]
I managed to replicate the same behaviour in Chrome.
