### ISSUE TITLE
Explain untriggered threats

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#110]
Threats that require a triggering CSG but are not triggered are shown in threat lists with the likelihood and system risk levels as "N/A". Because of this they generally appear at the end of the list so are often not seen.

If you hover over the "N/A" the tooltip says "Not yet available - please run risk calculation": this is misleading.

A simple change would be, for untriggered threats, to change the tooltip to "This threat poses no risk as it has not been enabled by a control strategy".

**Comment by scp93ch** [comment]
The threats also need explaining in the Threat Explorer. For instance, the the threat about the user forgetting their password:



![Image](https://github.com/Spyderisk/system-modeller/assets/4892991/fadde640-2b13-4577-bcf9-b5d695a0b472)

The triggering control strategy (the first in the list) needs separating from the other ones (see #109) but also at the top we should clearly state that the threat is not "enabled" rather than showing the likelihood and system risk.

Example model attached:

[test 2023-11-28T12_30.nq.gz](https://github.com/Spyderisk/system-modeller/files/13487921/test.2023-11-28T12_30.nq.gz)

**Comment by kenmeacham** [comment]
> Threats that require a triggering CSG but are not triggered are shown in threat lists with the likelihood and system risk levels as "N/A". 

Yes.

> Because of this they generally appear at the end of the list so are often not seen.

Are you saying that this is a problem?

> If you hover over the "N/A" the tooltip says "Not yet available - please run risk calculation": this is misleading.

Agreed. If the threat is not yet triggered then running a risk calc will make no difference (they will still display "N/A" afterwards.

> A simple change would be, for untriggered threats, to change the tooltip to "This threat poses no risk as it has not been enabled by a control strategy".

Seems reasonable.

**Comment by scp93ch** [comment]
The untriggered threats being at the end is not a problem , it's a bonus really

**Comment by kenmeacham** [comment]
> The threats also need explaining in the Threat Explorer. For instance, the the threat about the user forgetting their password:
> 
> ![Image](https://private-user-images.githubusercontent.com/4892991/286249252-fadde640-2b13-4577-bcf9-b5d695a0b472.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDYzNjMsIm5iZiI6MTcwMjMwNjA2MywicGF0aCI6Ii80ODkyOTkxLzI4NjI0OTI1Mi1mYWRkZTY0MC0yYjEzLTQ1NzctYmNmOS1iNWQ2OTVhMGI0NzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTQ0NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE2YjkwN2UzYTkyNGY4MDI0NjQxZTI3MDZmYzUxMWY5MjRiYTc4ZTViOWU0ZmJmMGI4NGUwYmFlYmYxMzNkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jyR0B4llY7reQ7orRnYL7ablHBmtjfDjaKRtzWX2q3Q)
> 
> The triggering control strategy (the first in the list) needs separating from the other ones (see #109) but also at the top we should clearly state that the threat is not "enabled" rather than showing the likelihood and system risk.

There is no triggering CSG displayed in your screenshot. Is this because they are only visible in developer mode?

> Example model attached:
> 
> [test 2023-11-28T12_30.nq.gz](https://github.com/Spyderisk/system-modeller/files/13487921/test.2023-11-28T12_30.nq.gz)

**Comment by scp93ch** [comment]
Perhaps I have got confused, but the threat in the screen shot is about the user forgetting their password. This threat will only be "triggered" if the password CS is present. The password CS is part of the first two CSGs and so these two are triggering CSGs. The final CSG is a "normal" CSG which helps reduce the threat likelihood (by providing a was to reset the password in this case).

**Comment by kenmeacham** [comment]
> Perhaps I have got confused, but the threat in the screen shot is about the user forgetting their password. This threat will only be "triggered" if the password CS is present. 

Password at "Adult", yes.

> The password CS is part of the first two CSGs ...

These are actually different control sets (CS). First one is Password at "WebBrowser", second is Password at "Adult"

> ... and so these two are triggering CSGs. 

I'm not sure this logic is correct (see further below)

> The final CSG is a "normal" CSG which helps reduce the threat likelihood (by providing a was to reset the password in this case).

Agreed.

If I turn on developer mode (Ctrl-#) and locate the threat (initially untriggered), I then see this additional "trigger condition" CSG in the list - "ClientUserStrongPasswordAccess". This is also indicated by the non-solid star icon, and it mentions the trigger in the text:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/23390025-b11c-4dae-8bb8-549b2a7c23b4)

We can see here that the 'Password at "Adult"' CS appears in 2 CSGs; one is triggered, one is not, so this CS is not enough to distinguish the triggered threat.

In the end, this all points to triggered threats needing to be explained better, which is the point of the issue :)

**Comment by scp93ch** [comment]
I got confused about the control strategies in the threat I was looking at: I agree that the ones I saw were not triggers for the threat. I had forgotten that the triggering CSGs were displayed with the empty star when in developer mode.

I will update #109 to make a better suggestion for how we display the CSGs.

On this issue, we agree about the tooltip (for the "N/A" text) and we need to have a sentence to display in the Threat Explorer description at the top that describes the situation of an untriggered threat.

In discussion on Teams, @kenmeacham and I agreed on placing this sentence just below the top title:

If it is untriggered:

"This threat is not currently active. It is triggered when a particular control strategy is enabled."

(We should leave the likelihood and risk level part present with the "N/A" along with the same tooltip agreed for the threats list.)

If it is triggered:

"This threat has been triggered by a particular control strategy which is currently enabled."

(In this case, the likelihood and risk levels will have actual values.)

**Comment by kenmeacham** [comment]
I've made some fixes, as discussed. Below are a couple of screenshots for the two cases:

1) Triggarable threat that has not yet been triggered
2) Triggered threat

You can see the status of the related triggering CSG in the screenshots too.

I took the liberty of making the text bold, adding "N.B." and positioning it just above the Likelihood and Risk values, as it seemed to be related to these. Hope you like this.

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/ba742555-18ec-4fa8-bfb0-a8c7bb56da4b)

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/6b2c5c1d-ad7c-40a4-8b16-8a9fa9484bb1)

**Comment by scp93ch** [comment]
Looks good Ken

**Comment by kenmeacham** [comment]
@scp93ch - did we agree that all threats should be displayed in the list (including the untriggered ones), so no longer just visible in developer mode?

**Comment by scp93ch** [comment]
> @scp93ch - did we agree that all threats should be displayed in the list (including the untriggered ones), so no longer just visible in developer mode?

I'm not sure if we agreed anything or not? As I understand it we do not show untriggered threats unless developer mode is on. If that's the case, I'd leave it as-is. There is an argument for showing an untriggered threat so you can see that it would cause a problem if some CSG was activated, but my feeling is that it's unlikely for someone to want/need to know that in advance.

**Comment by kenmeacham** [comment]
> > @scp93ch - did we agree that all threats should be displayed in the list (including the untriggered ones), so no longer just visible in developer mode?
> 
> I'm not sure if we agreed anything or not? As I understand it we do not show untriggered threats unless developer mode is on. If that's the case, I'd leave it as-is. There is an argument for showing an untriggered threat so you can see that it would cause a problem if some CSG was activated, but my feeling is that it's unlikely for someone to want/need to know that in advance.

The other option would be to hide them normally, but make them available via a filter (checkbox) in the threats list?

**Comment by scp93ch** [comment]
> The other option would be to hide them normally, but make them available via a filter (checkbox) in the threats list?

Good thought. I'd just leave it as-is for now though. I'm not convinced that (for a non-developer) there is even the need to add complexity to the UI by adding such a filter.
