### ISSUE TITLE
Add link to adaptor docs from the help menu

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#126]
Now we bundle the adaptor in by default, we should add a link to the OpenAPI docs:

`<application root>/adaptor/docs#/`

**Comment by kenmeacham** [comment]
I've added  an option from the Help menu, to view the Spyderisk Adaptor REST API, which opens in a new tab:

![image](https://github.com/user-attachments/assets/c0a4e182-591c-4d5b-9da2-6a22fdd1396a)

Tested via system-modeller-deployment with image 126-add-link-to-adaptor-docs-from-the-help-menu-latest
