### ISSUE TITLE
default domain model list is not persisted over service restart

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#161]
We have a bug in that in some circumstances, when a new user is added to an SSM instance (in Keycloak) the user cannot access the domain model(s) until the user is manually added to the ACL for the domain model(s) by the admin user.

The SSM can have multiple domain models installed for use at one time. Each domain model has a list of users who are permitted to use the domain model.

When a domain model is added to the SSM (either on initial boot, or later) the domain model is added as a zip file which includes the NQ file, a folder of icons and a JSON file which maps from asset to icon but also includes a field specifying whether the domain model is to be included in the list of domain models that users have access to by default (`defaultUserAccess`).

At some key points, the SSM synchronises the list of users it knows about with that held in Keycloak. Users that are new to the SSM are spotted and are authorised on all models in the default list. (Nothing is done about users in the SSM list but not in the Keycloak list, but that's another issue...)

If the SSM service is stopped and restarted (e.g. with docker-compose down / up) then the list of default domain models is lost. Presumably it should either be persisted, or recreated. If there are domain models loaded and the service is restarted, then you can see in the logs that in `InitializeManagementGraph:312` the service looks at the palette file it previously created in `/opt` but it does not appear to be looking at the `icon-mapping.json` file for the domain model in the same folder.

When this issue is seen, and a new user logs in, the following line (including typo) is seen in the logs:

```
WARN u.a.s.i.s.s.s.ModelObjectsHelper:1289: No default user demain models defined
```

There is also a separate issue that if a new domain model (with a different URI to the existing domain models) is loaded in, and the new domain model has the `defaultUserAccess` set to `true` then the ACL for the domain model should be initialised with all the existing users, but it isn't. The admin user will be able to use the new domain model (as there is perhaps no ACL check for that user) but none of the existing users can see it.

**Comment by scp93ch** [comment]
I suggest just disabling the check for whether a user is supposed to have access is supposed to have access to a domain model, and hiding the "Access List" button in the UI. I don't remember this feature ever being used.

**Comment by kenmeacham** [comment]
Users now have access to all domain models, and the Access List button has been commented out. A couple of unit tests are no ignored, now that the permissions have changed.

I tested by adding a new user, who was able to create a model OK without SSM complaining about access to domain models. Also restarting the service the permissions have not been lost, etc.
