### ISSUE TITLE
Triggered threats not always displayed in threats panel

### ISSUE THREAD

**Issue by kenmeacham** [SPYDERISK/system-modeller#172]
Whilst working on #109 and #110, we noticed some faulty behaviour. Basically, when enabling a triggering CSG on a threat, it should then be displayed in the threats list, whether in "normal" mode or "developer" mode. However, this is not the case, and is apparent also in the dev branch, not just the 110 branch. Interestingly the triggered threat DOES appear in the list after refreshing the page.

Triggerable threats that have not been triggered are only normally visible in developer mode. Once they have been triggered, they should be displayed in either mode (as per Blocked threats, etc). Currently in the dev branch, you would normally be in developer mode to locate an untriggered threat. Once triggered (in the Threat Explorer), the threat is uppdated correctly in the threats list. However, if you then go back to "normal" mode, the threat disappears. Generally the user would be remaining in developer mode once using it, so the problem wouldn't be observed. As said above, it is also not seen after refreshing the page.

Seems to be therefore a problem with the local update in the UI after setting a control in a triggering CSG.

**Comment by kenmeacham** [comment]
I've made a fix for this in the 110 branch, so this issue will be closed once this is merged in.

It turns out that this part of the code hadn't been updated since we moved from unique CSGs to shared ones. Previously each CSG had a type; now there is a map of types for related threats.

The result was that the triggered flag on a threat was never set, after triggering the CSG. However the flags were set correctly after reloading the model.

**Comment by scp93ch** [comment]
Good find Ken. It's probably worth checking if there are any other places that we're still assuming unique rather than shared CSGs. Perhaps you already did?

**Comment by kenmeacham** [comment]
> Good find Ken. It's probably worth checking if there are any other places that we're still assuming unique rather than shared CSGs. Perhaps you already did?

I've had a look through and can't find any reference to csg.type or csg["type"]
