### ISSUE TITLE
Attack path button not working

### ISSUE THREAD

**Issue by ross-campbell** [Spyderisk/system-modeller#19]
Dear SPYDERISK team, @scp93ch, 

I have been trying to deploy and use the SSM tool following the quickstart guide, and would like to report some issues found for your awareness.

*Using the main "dev" branch.

1. Localhost deployment - windows:
When deploying on a windows machine on localhost, the containers start ok, and the system modeller entry page can be accessed.
but when trying to login, i am redirected to "host.docker.internal:8081" instead of "localhost:8081" and therefore cant get past the keycloak login to the main dashboard.
   
   
2. Executing the gradlew command:
I can deploy locally and get though the login screen if i set in the .env file: DOCKER_GATEWAY_HOST=192.168.1.95 (my local ip).
However, when executing step 6 from the quickstart guide "./gradlew assemble bootTest", the command hangs at 94% 
"<============-> 94% EXECUTING [1h 11m 17s]"
Although, once the 94% has been reached, the UI can be accessed in a browser, and most functionality seems to work ok. I can validate a model and calculate the risks.

3. Show Attack Path
When selecting the Show attack path button - i am redirected to: 
http://192.168.1.95:8081/system-modeller/adaptor/api/v2/models/28pulfqdoqup659abafsgovprk7cvnd6jb7jaek60e4076i72e51olk2nu3ffiptlb84mpltgpbn99qlq18ucp3gv0ms1jasdccqi8v/path_plot?risk_mode=FUTURE&retain_cs_changes=false&direct=true&export_format=svg
Which displays the following json error message:
'
{
  "status" : 404,
  "error" : "Not Found",
  "message" : "No message available",
  "timeStamp" : "Thu Apr 27 11:17:45 GMT 2023",
  "trace" : null,
  "path" :  @"/system-modeller/adaptor/api/v2/models/28pulfqdoqup659abafsgovprk7cvnd6jb7jaek60e4076i72e51olk2nu3ffiptlb84mpltgpbn99qlq18ucp3gv0ms1jasdccqi8v/path_plot"
}
'

BR
Ross Campbell (ICE)

**Comment by scp93ch** [comment]
If you deploy Spyderisk with the latest version of the system-modeller-deployment project, then it will now automatically deploy the system-modeller-adaptor which currently does the attack graph plotting. With such a deployment, the attack graph button will work.
