### ISSUE TITLE
Metadata properties not handling long values correctly.

### ISSUE THREAD

**Issue by mirek186** [SPYDERISK/system-modeller#193]
When you store a metadata value that is longer than 80 characters, I don't know the exact number, but it needs to be long like an SSH key. In our case, the CSS stylesheet is not truncating the value, and therefore, the edit and delete buttons are no longer visible to edit the values. I've taken some screenshots and have proposed some solutions to fix it.

One of the potential fixes in AdditionalPropertiesPanel.js Add an option to hide overflow data so edit button is visible
In https://github.com/Spyderisk/system-modeller/blob/f8d2a7b058ce0936fd71e7c9d86982cd2a863ef3/src/main/webapp/app/modeller/components/panes/details/accordion/panels/AdditionalPropertiesPanel.js#L341
e.g.
https://jsfiddle.net/chathuramadhusanka/aNHa6/ 
https://stackoverflow.com/questions/10954188/html-text-display-limit-for-table-column
![Pasted image 20240629175001](https://github.com/user-attachments/assets/6f2a0acd-16da-4745-baa3-9de0c7d9390a)
![Pasted image 20240629175027](https://github.com/user-attachments/assets/12169e8a-9454-412b-b96e-c5cd2a7c1d88)

**Comment by mirek186** [comment]
I've looked into the stylesheet and as per screenshot below you could do all the changes inline the HTML. One way of doing it to add the following:
```
In table add style="table-layout:fixed;
<table style="table-layout:fixed;" class="table table-hover table-sm table-condensed">
In thead add width to Key and Value
<th width="160px">Key</th>
<th width="160px">Value</th>
And for each td add the overflow css style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;width: 10px;" 
<td style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;width: 10px;">
```
The red colour is only for visual effect.
![Screenshot_20240717_184054](https://github.com/user-attachments/assets/9db1434a-7fe3-4af5-84bd-cafb812ce64b)

**Comment by dgc** [comment]
Hi @mirek186,

Thanks for the report - I've fixed this issue and also tidied up the amount of space taken up by the action buttons on the end:

![image](https://github.com/user-attachments/assets/5df7d999-5cff-4efd-897e-7cd26d1ea4a6)
