### ISSUE TITLE
Fix the Risk Treatment Plan

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#2]
Trying to open the Risk Treatment Plan in the web UI currently results in a white-screen.

We need to make it work again and at the same time change the columns slightly:

* remove the "target date" column as this was only ever there as a mock-up
* add an "impact level" column (to be new column 2) to show the impact level of the consequence

Although there are other issues with the generated document, this is a sensible minimum to again have something useful there.

**Comment by kenmeacham** [comment]
To clarify, this is when selecting the "Risk Treatment Plan" option from the "Open Report" drop-down menu.

After the "white screen", the GUI is then unusable, so the modeller page needs to be reloaded in order to continue.

**Comment by kenmeacham** [comment]
The white screen glitch has been fixed and the columns changed as requested. The updated Risk Treatment Plan now appears as in the following example:

![image](https://user-images.githubusercontent.com/50845365/232729379-cabe9078-f8a5-4cc0-bca4-2bc70b5a2706.png)

**Comment by scp93ch** [comment]
I think it would also make more sense to relabel the "Threats" column to "Direct Causes" as that is what we now call them in the Consequence Explorer. Otherwise it looks like we may be listing all the Threats that cause this Consequence.

**Comment by scp93ch** [comment]
Known problems with the risk treatment plan:

- [x] The plan does not update to match an updated risk calculation unless you reload the model editor page
- [x] The "Threats" column would be better called "Direct causes"
- [x] When an inferred asset label appears in a threat description it is truncated at the first space, e.g. `Remote root access from "[SocketLAN`
- [x] The Consequences are not sorted in any logical order. They should be sorted alphabetically and, within that order, Consequences with controls should come first.
- [x] The lists of Threats do not appear to be sorted, they should be alphabetical.
- [x] The report just lists asserted assets and so misses any Controls on inferred assets. Perhaps we could also display any inferred assets where there is at least 1 Control.
- [ ] We should probably have an Excel export option, with the first column being the asset so that you could then use Excel table filtering etc.
- [x] The coverage level of Controls is not shown.
- [x] The population size of Assets is not shown.
- [x] The type and description of Assets should also be shown
- [x] Show Impact, Likelihood and Risk columns for each Consequence

**Comment by kenmeacham** [comment]
> Known problems with the risk treatment plan:
> 
>     The plan does not update to match an updated risk calculation unless you reload the model editor page
> 

Could you clarify which part(s) of the plan are not updating for you after a risk calculation?

**Comment by kenmeacham** [comment]
> > Known problems with the risk treatment plan:
> > ```
> > The plan does not update to match an updated risk calculation unless you reload the model editor page
> > ```
> 
> Could you clarify which part(s) of the plan are not updating for you after a risk calculation?

I've looked into this some more. Do you actually mean that the report is not being updated after setting controls? For example the Treatment Method, Status and Controls values? I'm not sure if running the risk calc makes much difference to these values.

**Comment by scp93ch** [comment]
> > > Known problems with the risk treatment plan:
> > > ```
> > > The plan does not update to match an updated risk calculation unless you reload the model editor page
> > > ```
> > 
> > 
> > Could you clarify which part(s) of the plan are not updating for you after a risk calculation?
> 
> I've looked into this some more. Do you actually mean that the report is not being updated after setting controls? For example the Treatment Method, Status and Controls values? I'm not sure if running the risk calc makes much difference to these values.

Sorry, I just don't remember what I observed.

**Comment by kenmeacham** [comment]
> > > > Known problems with the risk treatment plan:
> > > > ```
> > > > The plan does not update to match an updated risk calculation unless you reload the model editor page
> > > > ```
> > > 
> > > 
> > > Could you clarify which part(s) of the plan are not updating for you after a risk calculation?
> > 
> > 
> > I've looked into this some more. Do you actually mean that the report is not being updated after setting controls? For example the Treatment Method, Status and Controls values? I'm not sure if running the risk calc makes much difference to these values.
> 
> Sorry, I just don't remember what I observed.

I've fixed a problem that the report was not being updated to reflect changes in Controls. I don't see any issues after risk calculation, e.g. the risk values are not being shown anyway.

I also discovered that it was not distinguishing between triggered and normal threats, so I've made a fix for this on the server side.

**Comment by kenmeacham** [comment]
One feature that I've discovered about the Risk Treatment Plan may be a more serious issue (flaw in the design?).

At the moment, assets are displayed at all in the report if they have associated consequences (misbehaviours). For these, consequences are only shown if they have Direct Causes that themselves have a Control Strategy (i.e. having controls that can block/mitigate the threat).

This is fine in a lot of cases, but a particular threat might be mitigated by a Control Strategy on a Threat that is further up the chain. The result at the moment is that this consequence is not displayed in the table, even if it is being mitigated by a Threat that is not the direct cause.

Should this be improved? We could (in the first instance) report Consequences that do NOT have a Control Strategy on their Direct Cause. We might call this list "Uncontrolled".

In one of our current test cases, the asset of interest has several associated consequences, which have High impact. However, as none of these have Control Strategies, the whole asset is left out of the report. One current workaround is to "Accept" the direct cause for these consequences, which then makes the asset table appear. A preferable solution might be what I suggested above.

CC @mike1813, @scp93ch, @samuelsenior

**Comment by kenmeacham** [comment]
I have added likelihood and risk columns, so the latest output now appears as follows:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/24fc5e83-58d9-4fb3-87ad-c2da6f6adeb9)

N.B. Where a Direct Cause has no Control Strategy, this is now listed in the table where Treatment Method is reported as "n/a"

**Comment by scp93ch** [comment]
Looks great.
