### ISSUE TITLE
Add simple entity API

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#20]
We need a simpler API for the system modeller service, designed to allow read and possibly write access. Proposed that this be based on the following principles:

- each system model has a separate endpoint for read access to each type of entity contained in that system
- each should support a request for one entity (by specifying its URI as an argument), or all entities of that type (by specifying no argument)
- the response should contain one or more entities represented as resources, with a URI and a set of properties
- each property should be a single value or a list of values, where each value is a literal or another entity's URI, never an embedded entity.

System model entities have some properties that refer to domain model entities, e.g. a Threat and CSG entities have a `core#parent` property referring to the domain model type of which they are a subtype, while ControlSets, MisbehaviourSets and TWAS all have references to a domain model Control, Misbehaviour or TWA type. For this reason we will need the API to support the relevant domain model entity types. In this respect:

- the system model endpoint for a domain model entity should return entities from the domain model used to build and validate that system model

It should not be necessary to find out which domain model was used and send requests to a separate domain model API.

If we need a simple API for write access, I would propose a similar approach:

- a separate endpoint for each entity type that can be asserted (i.e., assets and relationships a.k.a. Cardinality Constraints)
- requests should include an entity, serialised according to the same principles as above
- the submitted entity will be added to the model as a resource, overwriting any previous resource with the same URI if there is one
- there should be no write access for system entity types created by the validator (most things including Threats, CS, MS, TWAS, CSGs, etc)
- there should be no write access for domain model entity types

Finally, the above API is almost identical to that of the JenaQuerierDB class, so it may make sense to implement it directly in terms of that.

*Note: this issue was originally authored by @mike1813 in an IT Innovation internal tracker.*

**Comment by scp93ch** [comment]
The main advantage of using the JenaQuerierDB is that it provides the Validator and Risk Calculator their method of access to the triple store. If changes are needed in any of the entity deserialisation classes (e.g. adding new properties), they would immediately become available to clients through this API.

The main disadvantage is that properties could not be removed or altered until all clients have been updated. This may lead to some baggage being retained in the Validator and Risk Calculator, but the advantages would seem to outweigh this disadvantage.

There are some issues that may need to be addressed if this approach is to be used, however:

- The JenaQuerierDB class has a construction and initialisation sequence that creates state needed to support some functions for the Validator and Risk Calculator, but only some of it is likely to be useful in a simple API.
- The JenaQuerierDB uses a cache for entities loaded from the triple store. It would therefore make sense to instantiate a querier per client session, so the client can benefit from caching and avoid reinitialisation when making a sequence of requests.

The state created in the start up sequence includes things like a domain model concept inheritance tree. This may be useful in the simple API, but other state would probably not be. It should be fairly easy to move anything not useful to a separate method to be called when required (i.e. by the Validator or Risk Calculator).

@scp: any thoughts?

* Note: this was authored by @mike1813 in an IT Innovation internal tracker. *

**Comment by scp93ch** [comment]
I think we should put all this in a new "Entity Controller" so that the endpoints are e.g. `/models/<modelID>/entity/threats/<systemThreatID>`

We need to carefully choose the entity names for the API, distinguishing system model and domain model (I agree we should be able to query the domain model entities via the system model). I suggest endpoints such as 

`/models/<modelID>/entity/domain/threats/<domainThreatURI>`

and

`/models/<modelID>/entity/system/threats/<systemThreatURI>`

We can use the short-form URI, e.g. `system#DS.C.HDS.1.3-MP-HDS_9c7b73ae_5959653d_e4ff7754_e4ff7754` rather than `http://it-innovation.soton.ac.uk/etc/etc/system#DS.C.HDS.1.3-MP-HDS_9c7b73ae_5959653d_e4ff7754_e4ff7754` as the identifier is already in the context of a model where the first part of the full URI is defined and unique.

Regarding the `JenaQuerierDB` discussion, I don't currently know enough to comment. I need to review it. We certainly do need to make sure this is fast and not spend time repeatedly initialising things like caches that are then discarded. Caching can be done outside of the service with e.g. [Redis](https://redis.io/) which might be more appropriate. We could optimise once it is working rather than immediately.

We should also take care of ensuring that our HTTP clients and services (e.g. Tomcat) are up to date with the latest specs so that we can take advantage of [HTTP3](https://en.wikipedia.org/wiki/HTTP/3) which massively reduces the connection start-up time for SSL handshakes etc and would become more important with lots of small client requests.

It would be useful to be able to request multiple entity URIs, of one type or even of several types. This can either be done in the request body (problematic as the behaviour of GET requests with request bodies is undefined), or in the query-string which has a maximum usable size of 2000 characters so quite a few URIs could fit.

We could also have the endpoints accept GET requests such as:

`/models/<modelID>/entity/domain/threats?id=<domainThreatURI1>,<domainThreatURI2>,<domainThreatURI3>`

But single resources should be done first.

**Comment by panositi** [comment]
Do we still need to speficy `modelID` for domain model entities?

**Comment by panositi** [comment]
Another question @kenmeacham @scp93ch . The current API has separate controllers for almost each entity, e.g. ThreatController, AssetController, UserController, etc. From the client side, each of these controllers should be instantiated separately in order to have access to specific API calls, eg threatController.getThreats()...

Do you see the new API extend those controllers or have another single controller for all those simple entities?

**Comment by scp93ch** [comment]
> Do we still need to specify explicitly `modelID` in the API URI for domain model entities?

Yes, because the domain model is in the context of a system model. As it says in the issue description "the system model endpoint for a domain model entity should return entities from the domain model used to build and validate that system model".

**Comment by scp93ch** [comment]
> Another question @kenmeacham @scp93ch . The current API has separate controllers for almost each entity, e.g. ThreatController, AssetController, UserController, etc. From the client side, each of these controllers should be instantiated separately in order to have access to specific API calls, eg threatController.getThreats()...
> 
> Do you see the new API extend those controllers or have another single controller for all those simple entities?

I think we need a new "Entity Controller" (see comment above).

**Comment by panositi** [comment]
@scp93ch, @mike1813, @kenmeacham the proposed simple entity REST API has the following calls:

http[s]://<spyderisk-host>//system-modeller/models/<model webkey>/entity/[system|domain]/...

```
/models/{modelId}/entity/system/threats/{systemThreatURI}
/models/{modelId}/entity/system/threats

/models/{modelId}/entity/system/consequences/{consequenceURI}
/models/{modelId}/entity/system/consequences

/models/{modelId}/entity/system/controlstrategies/{controlstrategyURI}
/models/{modelId}/entity/system/controlstrategies

/models/{modelId}/entity/system/controlset/{controlsetURI}
/models/{modelId}/entity/system/controlset

/models/{modelId}/entity/system/assets/{assetURI}
/models/{modelId}/entity/system/assets

/models/{modelId}/entity/system/trustworthiness/{twaURI}
/models/{modelId}/entity/system/trustworthiness


/models/{modelId}/entity/domain/controls/{controlURI}
/models/{modelId}/entity/domain/controls

/models/{modelId}/entity/domain/consequences/{consequenceURI}
/models/{modelId}/entity/domain/consequences

/models/{modelId}/entity/domain/{metric}/{impactLevelURI}
/models/{modelId}/entity/domain/{metric}
```

Where `metric` is `[likelihood, risk, population, impact, trustworthiness]`. The returned values are either a sinle entity DTO object or a list of entity DTO objects.

**Comment by scp93ch** [comment]
Following further discussion we agreed that the API endpoints and the content of the returned JSON should be consistent. For example, the JSON for a threat would (presumably) include references to "misbehaviour" but currently the endpoint is called "consequences" (plural). "consequences" is a good term for the UI, but people using the API (a) need precision/specificity and (b) can be expected to read documentation describing what the entities are.

We should therefore use the same words as in the core ontology.

The fields in the JSON returned by the entity API endpoints use the core ontology words, sometimes made plural: 

```
/system/threats has `mitigatedByCSG`, `directMisbehaviours` for instance
/system/consequences has `misbehaviour`
/system/controlstrategies has `controlSets`
```

The endpoint changes to make are therefore:

```
/models/{modelId}/entity/system/consequences -> misbehaviourSet
/models/{modelId}/entity/system/controlstrategies -> controlStrategies  (change in capitalisation)
/models/{modelId}/entity/system/controlsets -> controlSets  (change in capitalisation)
/models/{modelId}/entity/system/trustworthiness -> trustworthinessAttributeSet
/models/{modelId}/entity/domain/consequences -> misbehaviour
```

In addition, the JavaDoc on these endpoints need to be well written to describe what they are, including that e.g. "trustworthinessAttributeSet` is sometimes abbreviated to "TWAS" and that "controlStrategy" to "CSG" (this one especially as "CSG" appears in a field name).

**Comment by scp93ch** [comment]
@kenmeacham @panositi and I discussed some aspects of this API just now.

Some objects include data from the asserted and inferred graphs and the combination of the fields needs to be included in the response:
* ControlSets have data in the asserted graph representing the orange/green traffic lights
* MisbehaviourSets have the asserted impact level in the asserted graph
* TWAS have the asserted trustworthiness level in the asserted graph

The `assets` endpoint now returns asserted and inferred assets. We agreed that it would be useful for clients to be able to distinguish between them. An additional field could be added to the asset structure to say whether it is asserted or not. If this is easy to do then we should do it but otherwise log an issue and move on.

The ControlStrategy object should have its effectiveness and a list of ControlSets that relate to it. It would be useful for the ControlStrategy object to have a flag showing whether all the ControlSets are "proposed" or not. However, this can be discovered by the client by querying each ControlSet so it is not essential and should not be done yet (so just log an issue instead).

**Comment by panositi** [comment]
All 'attackPath' and 'recommendation' implementations check CS explicitly to determine whether a CSG is proposed or not.

**Comment by scp93ch** [comment]
> All 'attackPath' and 'recommendation' implementations check CS explicitly to determine whether a CSG is proposed or not.
> 
> ControlSets return `ControlSetDB` objects which do not cover much of asserted attributes.

That's useful to know. We certainly don't need to add an additional calculated field to the ControlStrategy. There's a danger of adding things in "because they're useful" when the API is supposed to be "simple"...
