### ISSUE TITLE
Bug in control coverage in the risk calculator

### ISSUE THREAD

**Issue by mike1813** [SPYDERISK/system-modeller#215]
The blocking effect of a control strategy is supposed to depend on:

- an intrinsic blocking effect for that type of control strategy reflecting how well it should work, and
- the coverage levels of any mandatory controls

As far as I can tell, the second dependency is not being calculated correctly in the risk calculator. The attached model (a test case created for #214) is very simple and should work with any v6a domain model. It involves a private space accessible from a public space. The public space has low assumed OccupantTW, meaning people able to occupy that space are not trustworthy. This leads to the behaviour PhysicalIntrusion in the private space, caused by a threat of these untrustworthy members of the public being able to enter the private space.

[Issue 214 Test 01 asserted.nq.gz](https://github.com/user-attachments/files/17560720/Issue.214.Test.01.asserted.nq.gz)

There is a control strategy that should block the relevant threat, that involves implementing a ChipAndPinLock control at the private space. The blocking effect of the control strategy is 'Safe', and the default coverage level for the ChipAndPinLock control is also 'Safe'. Selecting this control therefore prevents PhysicalIntrusion being caused in the private space.

However, if we override the coverage level of the ChipAndPinLock control to (say) 'Medium', there is no change in the likelihood of PhysicalIntrusion into the private space. Having a lower coverage level for a mandatory control should reduce the blocking effect of the control strategy, but this does not seem to work correctly.

**Comment by mike1813** [comment]
Turns out this is an old issue, see #124. It may also need to be investigated in conjunction with #76, although I thought that one was already addressed.

**Comment by scp93ch** [comment]
I've fixed this and attached the full model showing the likelihood level of PhysicalIntrusion is Medium when the coverage level of ChipAndPINLock is Medium. I first verified that before the fix, the likelihood level of PhysicalIntrusion was Negligible.

[Issue 214 Test 01 2024-11-05T14_51.nq.gz](https://github.com/user-attachments/files/17634421/Issue.214.Test.01.2024-11-05T14_51.nq.gz)
