### ISSUE TITLE
Review and improve docker-compose scripts

### ISSUE THREAD

**Issue by mike1813** [Spyderisk/system-modeller#26]
The current mechanism for configuring a service host name and IP address is less than satisfactory.

There is a variable ```DOCKER_GATEWAY_HOST``` which can be set in a (tracked) file ```.env```. However, this has two flaws:

- local configuration changes should not be in a tracked file.
- the value specified for this variable is not actually the service host name.

If this variable is set by altering ```.env```, the value is used to create the URL used by system-modeller to access the KeyCloak service. This URL is also inserted into some responses sent by system-modeller to its clients, giving them a means to access KeyCloak. If the variable is not set, the KeyCloak URL is created using a default host name ```host.docker.internal```.

The default hostname was chosen because it deals with the case where one is running on Windows using Docker Desktop. In that case, Docker Desktop creates a VM as the docker host, and adds an entry to the Windows ```...\etc\hosts``` file mapping ```host.docker.internal``` to a valid IP address of the Windows host. This means users can run a client on the Windows host, and specify ```host.docker.internal``` as the hostname for both the system-modeller service and the associated KeyCloak service. Docker Desktop uses vpnkit to connect between the docker host VM and the Windows host, so requests to services managed by Docker Desktop are forwarded to the right container. Meanwhile, when system-modeller contacts KeyCloak, it also ends up sending the request via the Windows Host, which gets forwarded via vpnkit in the same way.

Under Linux, the Linux host is also the docker host. Requests from clients running on the Linux host don't need to be forwarded to the docker host before they can be forwarded to the right container. The only issue is the connection from system-modeller to KeyCloak. To deal with this, the ```DOCKER_GATEWAY_HOST``` variable can be set to the IP address of the docker host on its internal subnet, which is always 172.17.0.1. System-modeller can send this back to the client as the hostname of the KeyCloak service, because this IP address is also a valid address of the local host. No hostname is required to access system-modeller or KeyCloak, whether from a client running on the Linux local host or from a container running under docker. No hostname is required.

The problem comes when clients are not running on the docker host. Setting ```DOCKER_GATEWAY_HOST``` = 172.17.0.1 doesn't work because this will then be sent back to the client as the hostname of the KeyCloak service, but KeyCloak can't be reached on this address from a remote client. Setting it to a hostname like ```host.docker.internal``` also doesn't work, because the client won't be able to find the IP address from this hostname. This is true even when the client running on a Windows host, and the docker host is a VM created using Hyper-V, unless the docker host was set up by Docker Desktop.

What we need is a mechanism to specify the host name of the docker host as seen by external clients, and ensure that the same host name is used inside the system-modeller container when referring to the KeyCloak service. External clients should be able to get an IP address for the docker host from this hostname in all situations:

- when the docker host is the client host
- when the docker host is a VM running on the client host
- when the docker host is a separate Linux system.

System modeller should also be able to look up the same host name and get the docker gateway IP address = 172.17.0.1, as seen from inside containers hosted by docker. This means we need a way to insert this IP address inside the container for whatever host name was specified for use by external clients.

To fix these issues we should make the following changes:

- [ ] The tracked ```.env``` file should be replaced by ```.env.template``` which can be copied to create an untracked ```.env``` in which local configuration options can be specified
- [ ] The ```DOCKER_GATEWAY_HOST``` variable should be replaced by something like ```SERVICE_HOST```, which should be set to a host name that can be resolved to an address for the service by external clients.
- [ ] This variable should also be used to create the KeyCloak service URL used by system-modeller both to connect to KeyCloak and to refer to KeyCloak in responses to external clients.
- [ ] This variable should also be used in the docker compose script used to deploy the containers to inject an ```/etc/hosts``` entry inside the SSM container (the one running the system-modeller service) mapping the specified host name to the gateway address 172.17.0.1.
- [ ] The build and deployment scripts should work in the same way if there is no local ```.env``` file, i.e., all variables that can be specified using this file should have default values.

It would make sense to use ```host.docker.internal``` as the default value for the service host, this the Docker Desktop set can still be used when deploying on a local Windows machine using that mechanism.

**Comment by mike1813** [comment]
@scp93ch : I'll take a quick look at the scripts used to deploy when not operating in developer mode. If I see any conflicts I'll add them here.

**Comment by mike1813** [comment]
It looks like the system-modeller-deployment version of the scripts would work much better, because there the KeyCloak URL is constructed from the $SERVICE_DOMAIN. This is actually the hostname of the service, so it matches my proposal.

Of course, an operational deployment may need to use an external KeyCloak service, so that version of the scripts must handles more variations than the one I proposed here. The one I proposed here is only appropriate for developers wishing to modify and test their own instance of the service.

That said, I think it would make a lot of sense if the developer version was based on the deployment version. We just need to take out support for configurations that don't make sense in developer mode, e.g., those that don't have their own dedicated and hence disposable KeyCloak and MongoDB services...

**Comment by scp93ch** [comment]
Following up on the discussion earlier today, the new GitHub CI workflow does use the "test" overlay for docker-compose. We therefore probably need to keep the current arrangement of a base `docker-compose.yml` file, the "override" file to configure the dev environment and the "test" file to configure the test environment.

We should add a reverse proxy (as we have in system-modeller-deployment) so that documentation and keycloak admin links work.

The dev config is of course complicated by the additional ports opened for debugging of various sorts and the persistent volumes.

We agreed that we should take the approach of exposing settings that a developer often needs to change as an environment variable so that this can be set in the user's (untracked) `.env` file. We should provide sensible fallbacks in the case that the developer does not provide a value.

An example of this would be to expose the "restart.on.boot" parameter currently set in the `application.properties` file.

**Comment by scp93ch** [comment]
Fixed and merged to dev
