### ISSUE TITLE
Show a summary of the attack graph for a Consequence in the web UI

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#3]
We want a user to be able to more easily understand the attack graph leading to a Consequence. Ultimately, some graphical interactive tree may be good, but initially we can provide some value by just displaying a list of threats leading up to a Consequence.

As this is in the context of an individual Consequence of interest, the information should be displayed in the Consequence Explorer. We will need a new "Attack Graph" accordion element in the Consequence Explorer.

The attack graph has to be calculated by the service using the work being done in #1. This is not instant, so the user will need to click on a button to launch the calculation. We'd then (ideally) need a spinner while the calculation is done. Once the data is returned, the button should be hidden and replaced with the data. We should (ideally) cache the returned data in the web client but the cache would have to be dropped as soon as any assertions about the system model are changed.

We can start with the very simplest representation of the data, showing it as a flat list, e.g.:

```
This consequence is cause by the following attack graph:
1: Description of threat that causes it
2: Description of threat that causes it
3: Description of one threat that causes it
3: Description of another threat that causes it
4: Description of root cause threat
```

where the numbers are the distance from the target Consequence (as returned by the API).

Each line should link to the threat in the Threat Explorer.

**Comment by mike1813** [comment]
Discussion today (17Apr) concluded that this can be done by extending the existing code for displaying threat lists. The natural sort order would be descending by distance to the target Consequence (the one displayed in the Consequence Explorer), but a system modeller user would be able to select other sort options.

We also concluded that it may be useful to provide an extra filter option, whereby threats are displayed only if downstream of a selected root (or initial) cause threat. This cannot be done as part of the initial development, however.

**Comment by mike1813** [comment]
@panositi : adding risksValid to ModelDB causes a problem.

The risksValid flag starts with value 'false', and is changed at the end to 'true' if the risk calculation was completed without an error. The deserialized value in ModelDB is therefore set to 'false'. This has two effects:

- The value 'false' is still present when the cache is synchronised to the triple store.
- The value returned to the client is probably also 'false'.

The client wasn't expecting any value to be returned at this point so I doubt the second effect causes a problem now, but it might later on if the client starts using that value for anything.

The first issue could cause problems though. The value 'risksValid = true' will still be added to the asserted graph after the risk calculation has finished, but that means we end up with 'true' in the asserted graph and 'false' in the inferred graph. I'd imagine that could cause problems later.

I recommend that you set model.risksValid to 'true' just before the end of RiskCalculator.getRiskCalcResults(). That way the client gets a sensible answer (if the response gets back, it will say risksValid=true). We'll still have duplicate triples, but they should be consistent.

**Comment by mike1813** [comment]
At some point we should sort out the mess in ModelDB. We really shouldn't be saving anything as a property of the static URI that signifies 'system model'. The URI referring to any system model should be its graph URI...
