### ISSUE TITLE
Default risk calculation modes

### ISSUE THREAD

**Issue by mike1813** [SPYDERISK/system-modeller#48]
The option to run a risk calculation without saving the results was introduced to support iterative recalculation in an automated search to find control strategies where speed is of the essence. It wasn't meant as a U/I option, though it may be useful if one is in a hurry.

Propose that we retain the ability to initiate risk calculations from the U/I with or without saving the results, but revert to saving the results as the default option.

This issue is independent from issue #3, but it turns out that would work better if risk calculation results were normally saved by default. This issue should be addressed in the changes for the associated branch and pull request.

**Comment by kenmeacham** [comment]
This has been fixed via a commit to branch #3

CC @panositi , @scp93ch
