### ISSUE TITLE
U/I Display Risk Calculation Mode

### ISSUE THREAD

**Issue by mike1813** [Spyderisk/system-modeller#49]
The U/I client should store and display the core#riskCalculationMode value ('CURRENT' or 'FUTURE') from the risk calculation response message.

The results from a risk calculation depend on which mode was selected. Risk calculations are always predictions about a future time window, but in a current risk calculation this window starts at the current time and doesn't take account of routine changes based on operating policies and practices such as software patching protocols, or discovery of vulnerabilities by attackers. In a future risk calculation, the time window is assumed to be far enough in the future that such changes will affect risk levels in either direction.

One cannot fully interpret the results of a risk calculation unless one knows which mode was used. The U/I therefore shouldn't display risk calculation results without the risk calculation mode, because the user as well as the U/I itself need to know which mode was used to get those results.

This issue is important in #3, because when one requests a threat path analysis in the U/I, it is done in relation to the displayed risk calculation results. The user needs to know if this is based on a current or future risk analysis, and the U/I client needs to tell the service to use the same option. However, strictly this issue is not part of #3, as it is important for other reasons.

**Comment by kenmeacham** [comment]
> Add riskCalculationMode to risk calc results

This task has already been done via commits on issue #3 (i.e. branch 3-show-a-summary-of-the-attack-graph-for-a-consequence-in-the-web-ui), where it was required more urgently.

**Comment by kenmeacham** [comment]
The following is taken from the original related issue: https://iglab.it-innovation.soton.ac.uk/Security/system-modeller/-/issues/1379 as reported by @mike1813:

At present, the SSM GUI displays model information in two places:

- in the dashboard, where models are listed and can be expanded to show more detail
- in the edit view properties panel under the title 'Model Details and Reports'

In neither place does the SSM GUI adequately display the risk calculation status. This has three possible states:

- risks have not been calculated
- future risks have been calculated
- current risks have been calculated

In the edit view, risk levels are not displayed if the system model is in the first of these states. However, if risk levels are visible one cannot tell whether they are current or future risk levels.

In the dashboard view, one cannot see any risk level status information unless one uses the expanded view. That specifies only whether risks have been calculated. As with the edit view, if risk levels have been calculated, there is no indication which type of risk calculation has been done.

Users do often need to know which state a system model is in, so this really should be addressed.

**Comment by kenmeacham** [comment]
Additional comment by @mike1813 on original issue:

@kenmeacham: I think this is one for you. I recommend the following.

In the dashboard, add a column to the listing headed something like 'Risk Levels'. The value displayed should be 'NONE', 'FUTURE' or 'CURRENT'.

In the edit view, add a line to the displayed system model properties called something like 'Risk levels calculated:', again with three possible values 'NONE, 'FUTURE' or 'CURRENT'.

In an ideal world, we would add a 'tool tip' to the risk level status value explaining what it means, at least in the edit view. That's really icing on the cake, though, so if it isn't easy, don't bother. If it is easy, let me know and I'll come up with the first draft of the tool tip text.

**Comment by scp93ch** [comment]
I'm not quite sure where Mike was proposing the state went when in the editor, but I'd put it in the Model Details part. You can tell from the risk calc button if you've run a calc or not so the key info is whether it is future or current. Generally someone will know which they have asked for recently so I don't think it is necessary to clutter the top bar with this info.

Please let's not put it all in capital letters.

**Comment by mike1813** [comment]
Just a note - I was anticipating that the type of risk calc would be added to the Model Details in the properties panel, as suggested by @scp93ch.

**Comment by kenmeacham** [comment]
> Just a note - I was anticipating that the type of risk calc would be added to the Model Details in the properties panel, as suggested by @scp93ch.

Yes, that is where I put the info, in the modeller page. Pull request for this has been submitted!
