### ISSUE TITLE
Tests fail in DomainModelControllerTest

### ISSUE THREAD

**Issue by kenmeacham** [SPYDERISK/system-modeller#5]
When running unit tests on the dev branch (on the initial commit), there are 3 broken tests in DomainModelControllerTest:

- testDeleteDomainModel
- testUploadNewDomainModelZipFile
- testUploadNewDomainVersionZipFile

All fail with a similar exception:

```
java.lang.NullPointerException
	at uk.ac.soton.itinnovation.security.systemmodeller.rest.DomainModelControllerTest.createMultiPartSpecZip(DomainModelControllerTest.java:189)
	at uk.ac.soton.itinnovation.security.systemmodeller.rest.DomainModelControllerTest.testUploadNewDomainVersionZipFile(DomainModelControllerTest.java:389)
```

**Comment by kenmeacham** [comment]
Further investigation shows that this is caused by 2 missing files

Folder: src\test\resources\domainmanager

Files:
domain-network-testing.zip
domain-network-testing-new.zip

**Comment by kenmeacham** [comment]
These 2 files were in the original source tree, prior to importing to Gitlab, however it seems that .zip files are currently ignored (see .gitignore)

It is likely that these were therefore originally added using the -f option in "git add"

These files need to be readded to the folder, but probably we should "unignore" them in .gitignore?

**Comment by scp93ch** [comment]
Yes, I agree. Unignore those files and commit them.
