### ISSUE TITLE
Reset-on-start behaviour

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#59]
We have an `application.properties` variable called `reset.on.start`. If it is set to `true` then the MongoDB database and triplestore are both wiped and reinitialised when the service starts.

The value of `reset.on.start` is now set in an environment variable (`RESET_ON_START`) by the `docker-compose.yml` file and defaults to `true` there. This means that changing the value in `application.properties` has no effect when using the docker orchestration and this is confusing.

**Comment by scp93ch** [comment]
As Spyderisk does not have to be deployed through docker-compose, it still makes sense to have `reset.on.start` in `application.properties`. We should put a comment there to warn developers not to bother changing the value there.

There are a few remarks about `reset.on.start` in the `README.md` file which should be corrected. we should explain that you should set the value in your own (untracked) `.env` file, or use `export RESET_ON_START=whatever` in the shell in the `ssm` container, or edit your `.env` file and `source` the file from the `ssm` container shell.

There was a suggestion that the default behaviour could be changed to be `false` which makes some sense as it's a safe default (non-destructive).

It's not clear how the production service is built or deployed any differently to the development one in this respect, so why doesn't the database get wiped in the production deployment? We have an `application-production.properties` file which sets the value to `false` but it's not clear that the spring profile is ever set to "production". It would make sense to understand this first...

The system-modeller-deployment [`docker-compose.yml` file](https://github.com/Spyderisk/system-modeller-deployment/blob/main/docker-compose.yml) does not set `RESET_ON_START`, nor does the `.env file`

**Comment by scp93ch** [comment]
When booting the system-modeller-deployment I get the log line

```
ssm                                    | 15:44:25.165  INFO u.a.s.i.s.s.SystemModellerApplication:655: The following profiles are active: production
```

That implies that the `application-production.properties` file will have been used and so `reset.on.start` is false. As it is not referenced in the docker or env files, it will be that value that is used.

**Comment by mike1813** [comment]
Ideally the system-modeller code should include an option to read the .env file (if one exists) and update the environment before starting the system-modeller itself.

I thought this could be done easily using the 'source' command. It turns out the shell is a bash-type shell, so the sequence of 'set VAR=value' statements from .env is insufficient. Each 'set' command must be followed by an 'export' command, so it isn't possible to just 'execute' the .env file in a simple way.

A script or maybe a gradle task to do this is presumably not all that difficult.

**Comment by scp93ch** [comment]
> It turns out the shell is a bash-type shell, so the sequence of 'VAR=value' statements from .env is insufficient

You can do `set -a; source .env; set +a`

**Comment by scp93ch** [comment]
I've found the last piece of the puzzle. In system-modeller `Dockerfile` the production build at the end includes the line `ENV SPRING_PROFILES_ACTIVE=production`. That explains why the production build does not reset-on-start (as it will use the value in `application-production.properties`.
