### ISSUE TITLE
Keycloak users are lost when container goes down

### ISSUE THREAD

**Issue by kenmeacham** [Spyderisk/system-modeller#64]
As occurred  yesterday, when attempting to upgrade SSM installation at: https://security.it-innovation.soton.ac.uk/system-modeller/, and fix issues reported in #63 ..

Apparently additional Keycloak users (i.e. those added subsequent to initial installation) are only stored in the running Keycloak container, and are not persisted anywhere. This is (relatively) fine if the container is stopped, as it can then be restarted, keeping the users. However, using `docker-compose down` removes the container and so all additional users are lost!

This is clearly very concerning, and could cause catastrophic problems when re-deployimg an SSM service that has many users.

The resulting effect here is that, although system models still exist in the MongoDB database, their associated user IDs no longer exist, so these models cannot be listed (even for admin user).

How should this be avoided in the future? Can we somehow persist the users, or back them up, prior to upgrade, etc?

**Comment by kenmeacham** [comment]
The emergency workaround for this yesterday was to manually edit the Model entries in the MongoDB database, to assign all system models with a new (existing) user id (e.g. for testadmin). This at least meant that the models could be listed in the SSM dashboard, however the original owners were lost.

**Comment by scp93ch** [comment]
This should perhaps be in the system-modeller-deployment project? For the system-modeller project we are just doing software development and testing of the service so having the Keycloak data not persisted is arguably okay.

The Keycloak configuration provided in the system-modeller-deployment project is clearly marked as an insecure example not to be used in production. We would expect installations of Spyderisk to link to a properly configured Keycloak instance.

If we wanted to persist the users in the insecure Keycloak config for the deployment, we could add:

```yaml
      # Persist Keycloak data
      - type: volume
        source: keycloak
        target: /opt/keycloak/data/h2
```

to the `volumes` entry of the `keycloak` container in `docker-compose.yml` and also add `keycloak:` to the list of volumes at the end of the file.

**Comment by kenmeacham** [comment]
> This should perhaps be in the system-modeller-deployment project? For the system-modeller project we are just doing software development and testing of the service so having the Keycloak data not persisted is arguably okay.

Yes, this is really an issue for a deployed service (using system-modeller-deployment), and I agree that a locally deployed Spyderisk does not really need to persist users, and that the bundled users are generally enough for most purposes.

> The Keycloak configuration provided in the system-modeller-deployment project is clearly marked as an insecure example not to be used in production. We would expect installations of Spyderisk to link to a properly configured Keycloak instance.

Confirmed. The comments in the scripts are quite clear. We might consider improving the Spyderisk docs if necessary.

> If we wanted to persist the users in the insecure Keycloak config for the deployment, we could add:
> 
> ```yaml
>       # Persist Keycloak data
>       - type: volume
>         source: keycloak
>         target: /opt/keycloak/data/h2
> ```
> 
> to the `volumes` entry of the `keycloak` container in `docker-compose.yml` and also add `keycloak:` to the list of volumes at the end of the file.

I discussed this with @panositi and this seems reasonable. However @panositi pointed out that the current entrypoint.sh script would still attempt to recreate the Keycloak realm when started up; we're not sure of the exact result here, but it may well remove any extra users that had been persisted! So some change to this script would be necessary..

The better approach is to use a separate/extermal Keycloak deployment, which is better configured to store (persist) its users. This has already been done by @panositi for the internal Keycloak service running at:
https://keycloak.it-innovation.soton.ac.uk/auth/
Here, we use a Postgres database, with a persisted data volume. Further details can be found in the keycloak-standalone project at: https://git.soton.ac.uk/it-innovation-centre-internal/systems/keycloak-standalone
N.B. This information is currently internal, but could be made available if necessary.

For the existing Spyderisk deployment at https://security.it-innovation.soton.ac.uk/system-modeller/ we are somewhat stuck with using the basic Keycloak installation (with the danger of users being lost when the container goes down). However we do now have a means of backing up users after creation, in case (or when) the container goes down.

TODO (@panositi) - please can you add details of the Keycloak users backup facility?

**Comment by kenmeacham** [comment]
See further guidance on upgrading a server and backing up here:

https://github.com/Spyderisk/system-modeller-deployment?tab=readme-ov-file#upgrading-a-deployment
