### ISSUE TITLE
MongoDB container fails after upgrade of SSM

### ISSUE THREAD

**Issue by kenmeacham** [Spyderisk/system-modeller#65]
Prior to migrating SSM to Github, the version of mongo changed, as follows (i.e. the image:version defined in the docker-compose.yml file used by system-modeller-deployment):

mongo:4.2.17-bionic -> mongo:5.0.16-focal

This quite major upgrade unfortunately seems to produce some incompatibility errors, after attempting to upgrade a server that had previous MongoDB databases using the older version.

During an attempted SSM service upgrade yesterday, it was necessary to downgrade the version of mongo used, in order to avoid these errors.

How can we then properly upgrade/migrate existing MongoDB tables, etc, so we can upgrade to the latest mongo without errors?

**Comment by kenmeacham** [comment]
@panositi - you said that you have a backup solution for a deployed Spyderisk service. Does this now solve this issue, as mongo data could be backed up prior to upgrading MongoDB to v5 (then re-imported)?

**Comment by panositi** [comment]
The backup solution will not work with old mongo-v4.2 installations  as the two docker images come from different providers the mongo service setup is different. There is a way to backup mongo databases from version 4.2 but practically this issue should be considered obsolete now?

**Comment by kenmeacham** [comment]
> The backup solution will not work with old mongo-v4.2 installations as the two docker images come from different 
providers the mongo service setup is different. 

OK..

> There is a way to backup mongo databases from version 4.2 but practically this issue should be considered obsolete now?

Well if there are no more old servers on 4.2 then yes. Is that what you're saying?

**Comment by kenmeacham** [comment]
See further guidance on upgrading a server here:

https://github.com/Spyderisk/system-modeller-deployment?tab=readme-ov-file#upgrading-a-deployment
