### ISSUE TITLE
Add control strategy recommendations API

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#67]
The system-modeller should have an API endpoint which takes as input a list of MisbehaviourSets and a target likelihood and returns a list of ControlStrategies which, if enabled, will reduce the likelihood of the MisbehaviourSets to at most the given likelihood.

**Comment by scp93ch** [comment]
The API endpoint should also have a parameter to say whether it is a current or future risk situation (in just the same way that the attack graph endpoint does).

**Comment by kenmeacham** [comment]
One problem that I'm having when developing the SSM UI for recommendations (#128) is that the returned value of "risk" in the recommendations report is not very usable by the UI, e.g.
```
risk: (RiskLevelHigh: 0, RiskLevelMedium: 1, RiskLevelVeryHigh: 1, RiskLevelLow: 1, RiskLevelVeryLow: 693)
```
Although this is human-readable OK, it is hard to extract the information in the UI. I think what we need is a data structure that uses the risk level URIs along with their counts, e.g.
```
{
  "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#RiskLevelVeryHigh" : 1,
  "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#RiskLevelHigh" : 0,
  "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#RiskLevelMedium" : 1,
  "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#RiskLevelLow" : 1,
  "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#RiskLevelVeryLow" : 693
}
```

We could also use the shortened URIs, e.g. domain#RiskLevelVeryHigh

The full risk level definitions are already available in the SSM UI, which is why the URIs are sufficient to identify them.

Does this seem reasonable? Feel free to comment.

**Comment by scp93ch** [comment]
Completely agree Ken. And the shortened URIs should be sufficient.

**Comment by panositi** [comment]
I can change the code for that, it will be two lines change but will provide the short version of the URI i.e. domain#RiskLevelLow for example

**Comment by kenmeacham** [comment]
That sounds fine. Shortened URIs are OK. The return type will need to change, as you said. Once we have this, we can more easily use the data in the UI, e.g. for ordering by risk/vector.

**Comment by scp93ch** [comment]
We just discussed that at the moment the endpoint does not have the parameters proposed in the initial issue.

# Fixing the endpoint

## Service 

The endpoint should have a parameter which is the "acceptable risk level" (or something similar) which is the risk level which when reached for all the target MS the algorithm will terminate. This should be a mandatory parameter because if we had a default then it would mean hard coding / configuring a value from a specific domain model in the service. The parameter should be the risk level URI.

The endpoint should have an optional parameter which is the list of target MS URIs. If the parameter is not supplied then the service should generate the list of MS by finding all MS which have a risk level higher than the acceptable level parameter (this is what it does now, albeit with the hard coded "Medium" level).

## Client

At the moment the recommendation is launched from the (visual) attack graph button, top-right. This means there is no opportunity to supply a parameter for the acceptable risk level. 

Options are:

1. When the user requests a recommendation from this menu we pop up a dialogue asking what acceptable risk level they want to pass in.
2. Put the acceptable risk level in the client config.

   i. Put it as "RiskLevelMedium" or "Medium"
   ii. Put is as "3"

For (2), either way the client can look up the risk level URI to pass to the service endpoint. 2.ii. is slightly less bad because even with a different domain model there would still be a risk level with value "2" whereas there may not be a URI ending with "RiskLevelMedium".

For minimal work I would suggest we go for 2.i. or 2.ii. (don't care too much).

I think ideally we would not have the recommendation launched from the attack graph button (although they relate to each other in the service, the user will probably not realise this). Instead I would have a new button which pops up a dialogue allowing the user to choose current/future risk and the acceptable risk level before launching the recommendation. Down the line you could extend that to allow a choice of target MS from the same dialogue.

Another small addition we can make to the client once the service endpoint is fixed is to provide a recommendation button on the Consequence Explorer. This would call the recommendation endpoint with a list of 1 MS (the one from the Consequence Explorer). Either just a button to get the recommendation using the default discussed above, or a button with a selectable acceptable risk level (where the choices would be limited to be below the current MS risk level).

# Stopping the task

With the recommendation algorithm as it is (whether it is buggy or just naïve, not clear yet) it can take a very long time to complete, or possibly never complete. We need to have a way to stop the task. This will require changes on the client and service.

**Comment by panositi** [comment]
> We just discussed that at the moment the endpoint does not have the parameters proposed in the initial issue.
> # Fixing the endpoint ...

The default URL value for the *acceptableRiskLevel* parameter should be defined in *application.properties* as a string of:
- `Medium`
- `domain#RiskLevelMedium`

Somehow it needs to be converted to the actual URI, or throw an error, that also includes the API endpoint as the user might provide not valid URIs.

**Comment by scp93ch** [comment]
>  that also includes the API endpoint as the user might provide not valid URIs.

What does this mean please? I don't know what "that" refers to, or why it needs to include the API endpoint, or what endpoint you mean.

**Comment by scp93ch** [comment]
> I mean parameters passed as string values should be validated against some sort of schema, should we use the simple form of risk levels for that eg _verylow, low, medium, high, and veryhigh_?

I proposed a couple of alternatives above. I suggested that using the integer (option 2.ii.) was slightly less bad than other options. I'm not sure why you're making additional suggestions for how to do it?

We know how to convert from any of these config suggestions to the actual URI because the client has a list of all the levels loaded in along with a system model. If what was in the config file could not be converted to a URI then we would indeed need to throw an error but that could only be done at the point of having a system model loaded (which is partly why having domain-specific stuff in the client or service is really not great).

You didn't explain what you meant about the "API endpoint"?

**Comment by scp93ch** [comment]
Following some discussion @panositi clarified that the [comment above](https://github.com/Spyderisk/system-modeller/issues/67#issuecomment-1959337399) was talking about the service, and input validation. We do not need to have a default acceptable risk level in the service (whether in Java or config file). I agree that the acceptable risk level argument to the risk assessment endpoint should be validated.

We discussed various options for making progress on this task.

1. @panositi should review the `scp-logging` branch (which was a mixture of bug fixes and logging improvements, but also a WIP) and potentially merge it in to #67.
2. @panositi explained that he had adjusted the recommendation algorithm to terminate the search if the global risk level increased upon applying one of the CSG options. This behaviour should be controlled by an argument in the endpoint. I suggest we have an argument `localSearch` which is `true` by default to make this behaviour the default.
3. The implementation of the MS list argument has been started but is not complete. Once (1) and (2) are done we should consider whether to postpone this aspect.

Regarding the method of not letting the risk increase, it is a shortcut which means we only find "local minima" rather than the global one. Practically, it means that we will not ever propose a CSG which has a side effect with a high risk level. 

The advantage of having the ability to pass a list of target MS is that again it reduces the search space but also, with the proposed `localSearch` parameter at `false` we could propose CSGs with side effects which did reduce the risk level of the target MS but also increased the risk level of something else. I would expect that if we limit the search to the target MS (and the termination condition only considers their risk level) then again, this would be quick, even with `localSearch=false`. Practically, the user would request a recommendation for 1 target MS, implement it and find that there was now a problem elsewhere to fix.

In terms of the UI for the list of target MS, we can initially simply have a button in the Consequence Explorer to request a recommendation for a list of 1 target MS.

**Comment by scp93ch** [comment]
Yesterday a few of us discussed the options for the recommendation search and there was a bit of push-back about the idea of only considering a list of MS.

My proposal was that if a list of target MS was supplied to the algorithm, it should only ever build an attack tree for those MS, and should stop (with success) when the risk levels of all the target MS were at or below the acceptable risk level.

This could have the effect of solving the problems associated with the target MS, but causing problems elsewhere by side effects. A recommendation could therefore actually increase the overall risk level. The argument for this was that at least in this way you would be presented with options that involved side effects. The user could choose one of these options and then fix the side effect as a next step. Otherwise the recommendation algorithm would only propose CSGs with significant side-effects if it also was able to simultaneously propose a fix for the side-effect and this would not happen with the local search (and the global search can take a very long time).

The possible alternative was to stop with success when the global risk level was acceptable (as we do when no target MS are supplied).

In fact, if we run the algorithm with a specified list of target MS and wait until the global risk level is acceptable then we can easily get into situations where no solution is found. For instance if you have 2 very high risk level MS and target just 1 of them then it is likely that the other MS will never be fixed.

In the commit just now I have adjusted the recursion success and failure termination conditions as such:

* Calculate attack tree:
  * If we have target MS then use these as the targets
  * Else find all MS above the acceptable risk level and use those as the targets
* For each CSG option from the attack tree:
  * Apply the CSG option
  * Compute current risk level
  * Check for success:
    * If we have a list of target MS then stop if the risk level of all target MS is acceptable
    * Else stop if the overall (highest) risk level is acceptable
  * Check for failure:
    * If we are doing the localSearch and the risk level has increased then stop (note that here we are comparing the counts in the risk vector, not the overall highest level, this could be softened to just stop if the highest level increases)
  * Recurse

**Comment by mike1813** [comment]
> Check for success:
> 
>     * If we have a list of target MS then stop if the risk level of all target MS is acceptable
> 
>     * Else stop if the overall (highest) risk level is acceptable

The second criterion implies the first, so the 'else if' clause would never be reached.

I propose switching them around, so later on we can make the 'else if' clause do something different, e.g., provide users a way to stop the process or continue for some time, or adjust the target MS list in some way. Meantime, we can just 'stop', of course.

**Comment by scp93ch** [comment]
My pseudocode was too abbreviated and therefore ambiguous so I think you've misinterpreted what I actually meant. This is what I meant:

* Calculate attack tree:
  * If we have target MS then use these as the targets
  * Else find all MS above the acceptable risk level and use those as the targets
* For each CSG option from the attack tree:
  * Apply the CSG option
  * Compute current risk level
  * Check for success:
    * If we have a list of target MS
      * stop if the risk level of all target MS is acceptable
    * Else
      * stop if the overall (highest) risk level is acceptable
  * Check for failure:
    * If we are doing the localSearch and the risk level has increased then stop (note that here we are comparing the counts in the risk vector, not the overall highest level, this could be softened to just stop if the highest level increases)
  * Recurse

**Comment by scp93ch** [comment]
As discussed on Teams, we decided to add a button in the UI to enable a recommendation computation for a single MS. This is very similar to the attack path calculation for a single MS. We could label it "Recommendation".

The button will go next to the attack path button in the Consequence Explorer. The arguments for the call to the recommendation endpoint (in no particular order) will be:

* targetMS list: [the MS of the Consequence Explorer we launch from] (same as for attack path button)
* risk mode: whatever the risk mode is in the last calculation, as found in the local model (same as for attack path button)
* localSearch: false (different to the other recommendation call)
* acceptable risk level: the one from the client config (same as for the other recommendation call)

Presumably (given the need to read the risk calculation mode from the model in the client) the attack path button is disabled until a risk calculation has been done (otherwise the property would be undefined). This new button would also need to be disabled with the same logic.

**Comment by scp93ch** [comment]
In order to be transparent about this feature, and how it is far from perfect, we agreed this morning that rather than just putting "beta" in the title of the Recommendations Explorer we should strengthen the warning.

I propose:
* Titling the window "Recommendations Explorer (work in progress)"
* Having text at the top of the explorer saying "The recommendation feature is a work in progress and will not always give the most sensible recommendation. It may also take a very long time to run, in particular for Future risk recommendations. A list of [known issues can be found on GitHub](https://github.com/Spyderisk/system-modeller/issues/140)."

One problem of course is that this text is only seen after the user has launched the recommendation calculation.

We also need to add documentation to the user docs.

**Comment by kenmeacham** [comment]
> As discussed on Teams, we decided to add a button in the UI to enable a recommendation computation for a single MS. This is very similar to the attack path calculation for a single MS. We could label it "Recommendation".
> 
> The button will go next to the attack path button in the Consequence Explorer. The arguments for the call to the recommendation endpoint (in no particular order) will be:
> 
>     * targetMS list: [the MS of the Consequence Explorer we launch from] (same as for attack path button)
> 
>     * risk mode: whatever the risk mode is in the last calculation, as found in the local model (same as for attack path button)
> 
>     * localSearch: false (different to the other recommendation call)
> 
>     * acceptable risk level: the one from the client config (same as for the other recommendation call)

Technically, this comment is more related to issue #128, but will reply here.

A new "Recommendations" button has been added into the "Attack path threats" panel, as requested. This uses the specified parameters to call the recommendations API, then open the Recommendations Explorer as before.

> Presumably (given the need to read the risk calculation mode from the model in the client) the attack path button is disabled until a risk calculation has been done (otherwise the property would be undefined). This new button would also need to be disabled with the same logic.

Agreed that the button should be disabled if risks are invalid (e.g. after setting a control). Actually the better flag to use is the riskLevelsValid flag on the model, so I've implemented this, and also fixed the adjacent "Calculate attack path" button, which wasn't behaving correctly.

**Comment by kenmeacham** [comment]
> In order to be transparent about this feature, and how it is far from perfect, we agreed this morning that rather than just putting "beta" in the title of the Recommendations Explorer we should strengthen the warning.
> 
> I propose:
> 
>     * Titling the window "Recommendations Explorer (work in progress)"

Done.

>     * Having text at the top of the explorer saying "The recommendation feature is a work in progress and will not always give the most sensible recommendation. It may also take a very long time to run, in particular for Future risk recommendations. A list of [known issues can be found on GitHub](https://github.com/Spyderisk/system-modeller/issues/140)."

Done (with very minor changes to text)

> One problem of course is that this text is only seen after the user has launched the recommendation calculation.

We can manage with this for now.

> We also need to add documentation to the user docs.

I think we should spawn another issue for this.

One other issue which I've addressed is that there may be many recommendations returned; in this case the UI grinds to a halt, trying to display everything. For now, I have added a MAX_RECOMMENDATIONS parameter (see constants.js) to restrict the number displayed initially. A typical display now looks like this:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/73cf5406-a09b-4ead-9808-4d666f3b5c15)

**Comment by scp93ch** [comment]
There have been discussions today with various people about the need and manner of cancelling recommendations tasks which can take a long time (hours even) and we are not sure if they actually always complete.

*What could go wrong?*

If we cannot cancel the task then it could go on forever and we'd have to abruptly stop the service and start it again. That could possibly leave some model(s) in a corrupted state (the model flag describing whether a risk calculation is going on for instance). Even if the model(s) were fine, it would create admin work for the person (e.g. us) running the service and an unreliable experience for the users.

*Do we need to have a cancel feature?*

* If we didn't have it, I would not want to merge the recommendations into main.
* If we didn't have it, I would not want to put such a service in front of a user (such as a project partner) in a shared service.
* We believe the feature is useful so not putting it in front of users because of a lack of cancellation facility would be a great shame.
* We could merge what we have on branch 67 into dev without the cancel feature, but then we wouldn't be able to deploy off dev or merge from dev to main to make any release until this was fixed so we might as well fix it now.

So yes, we need to be able to cancel the task.

*What are the means to cancel it?*

* We cannot necessarily rely on the user to cancel the job. Therefore the service itself needs to cancel the job if it has gone on too long.
  * We could stop after *n* calls to the `applyCSGs` function
  * We could stop after *t* seconds
  * We would ideally want to return whatever results had been found up to that point
* We ideally want the user to be able to cancel, rather than wait for the task to time out on the service.
  * Panos has already got code to do this (uncommited and untested)
  * Ken has already done work on how to interrupt the task on the web client side (though this is related to #128)

Regarding the endpoints for the recommendation job, at the moment the ones with the `jobId` in are in the wrong order:

* `/models/{modelId}/recommendations/status/{jobId}` should be `/models/{modelId}/recommendations/{jobId}/status/` for instance.
