### ISSUE TITLE
Make it possible to put an EULA on the Welcome page

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#87]
We need to be able to put an EULA on the welcome page, setting out the terms and conditions that someone accepts when using a Spyderisk deployment. The EULA will be different for different deployments so this must be done in a way that means it can be configured at deployment time (via system-modeller-deployment project).

Suggestion:
* the EULA is written in plain text in a file, with a default (built into the SSM source tree) saying just that the software is open source, licensed under Apache 2.0.
* the welcome page includes the plain text file inside a textarea with scroll bar, picking it up from the file using the Thymeleaf templating
* the system-modeller-deployment overwrites the default EULA with one supplied at deployment time if the location of an EULA is specified in the .env file

**Comment by kenmeacham** [comment]
I've made an initial version of this. Here are some screenshots to look at. The Welcome page has a link to a separate "End User License Agreement" page, as shown below. The EULA page is accessible via "/EULA" endpoint and has a link to the remote license. 

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/cb718e20-4c25-4ffd-a69c-884eacc09815)

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/80c652ca-ed91-4fe5-a047-c1dde390295b)

**Comment by kenmeacham** [comment]
The default EULA web page is stored in a file called EULA.html, contained within the templates folder (i.e. where welcome page itself is located). The filename is configurable via .env, so we could configure to point to a different file, e.g.

# EULA filename (i.e. filename without .html suffix)
EULA_FILENAME=EULA

N.B. Any alternative EULA file should currently be located in the same templates file within the ssm image

**Comment by scp93ch** [comment]
I think the EULA needs to be visible in the welcome page, not a link to it. That's why I suggested having the EULA in a textarea element of the page. We then wouldn't need to have the additional config to serve an additional page either.

It looks like thymeleaf can easily pull in a text string (e.g. the EULA) from a properties file: https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#using-thtext-and-externalizing-text

Can we just adjust the welcome page template to pull in a "txt" property with `<p th:text="#{eula.txt}"> from the property `txt` in file `/WEB-INF/templates/eula.properties` ?

I don't know if we'd be able to embed newlines in the text though?

We can then put a statement on the page saying "By logging in you accept the EULA above" or somesuch.

Within the system-modeller-deployment project we can write over the property file with the chosen EULA.

**Comment by kenmeacham** [comment]
I can add the EULA directly to the welcome page, but if I use a textarea it comes out like this (i.e. it can't render HTML):

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/5d5013de-db41-45a1-91bd-90d5ab1fb55b)

**Comment by scp93ch** [comment]
Yes, I was aware that a textarea would not support HTML. However, I guess we could just as easily use a DIV element, styled to be a certain size with a vertical scrollbar for overflow?

I think it is important to have the EULA on the page that someone sees before logging in.

**Comment by kenmeacham** [comment]
The EULA is now embedded on the welcome page in a scrollable div:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/ad3b51fd-b974-48ba-aa00-4022ac732f37)

**Comment by kenmeacham** [comment]
I have also added a DISPLAY_EULA parameter (true/false) to control whether the EULA is displayed or not.

Just running the tests..

**Comment by kenmeacham** [comment]
I've committed a fix to system-modeller-deployment (main) to add the parameters to .env, etc. Then retested using the latest SSM image after merging the #87 branch
