### ISSUE TITLE
Add link to API docs to the help menu

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#93]
The OpenAPI docs are available at /swagger-ui.html and they should be linked to from the help menu.

(This issue was #1405 in the internal tracker.)

**Comment by kenmeacham** [comment]
I got it to open the API docs via the help menu (not yet committed). Currently the menu looks like this. If you're happy with this, I'll check it in.


![image](https://github.com/Spyderisk/system-modeller/assets/50845365/a8a0b30e-8031-4bf2-9c87-8c7125bbcf88)

**Comment by scp93ch** [comment]
Looks fine.
