### ISSUE TITLE
Add way to reveal hidden Trustworthiness Attributes in UI

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#94]
Provide a way to reveal (in the SSM GUI asset properties) asset trustworthiness attributes (TWAS) whose TWA has an `isVisible` property set to False.

This feature will be useful anyway, but it will be essential once population support is added. The number of TWA types will increase by a factor of three, so the `isVisible` property will be used to suppress the display of extra highest and lowest level TWAS. But sometimes the user will need to check and update them.
Because this is a user requirement, and not a debugging (dev) requirement, it should not be connected to the SSM GUI ‘developer mode’ setting. Ideally, it should be a filtering option in the properties panel to hide the TWAS where the TWA property `isVisible==False`, but one where the filter is switched on rather than off by default.

(This issue was #1311 in the internal tracker.)

**Comment by kenmeacham** [comment]
Initial display of filter:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/6469e727-b40e-4c98-8587-4321887fdbe3)

**Comment by scp93ch** [comment]
Yes, as mentioned in the PR, can we change it to be "Hidden attributes" and unticked by default. It's easier to mentally parse that way. It's unusual to have a checkbox where unticking it displays more.

**Comment by kenmeacham** [comment]
Final look. See also PR:

![image](https://github.com/Spyderisk/system-modeller/assets/50845365/604ffac6-eea3-4be1-9c52-72b0cbab13ae)
