### ISSUE TITLE
Excessive logging at info level

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller#95]
A recent commit has resulted in excessive logging at INFO level when the validation runs.

The commit is:
https://github.com/Spyderisk/system-modeller/commit/ec2cd2a963ce32630ecacebf5106f67a35597762

In particular, the log message on line 1278 appears 100's of times on validation. Quite probably the message should be removed (as it is hit so many times). Perhaps the others should be put to DEBUG level?

**Comment by kenmeacham** [comment]
That particular commit had a "TODO" to remove the excess logging, which I forgot TODO :)
